name: boilerplate
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui  widgets
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3

  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  shimmer: ^2.0.0

  # other utils
  social_share: ^2.2.1
  equatable: ^2.0.3
  google_api_availability: ^3.0.1

  # state management
  flutter_bloc: ^8.0.1
  rxdart: ^0.26.0
  logger:

  # network
  dio: ^4.0.6
  http: ^0.13.4
  connectivity_plus: ^2.2.1

  #Social Login
  flutter_facebook_auth: ^4.1.2
  google_sign_in: ^5.2.4

  # data persistence
  shared_preferences: ^2.0.13

  # localization
  easy_localization: ^3.0.0

  #Firebase
  firebase_core: ^1.10.6
  firebase_messaging: ^11.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  change_app_package_name: ^1.0.0

flutter:
  assets:
    - assets/translations/
    - assets/images/

  uses-material-design: true

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
